app:
  dataSource:
    host: localhost
    username: obectron
    password: 7840
    databaseName: obectron
    jdbc-url: jdbc:postgresql://${app.datasource.postgresql.host}:${app.datasource.postgresql.port}/${app.datasource.postgresql.databaseName}

spring:
  application.name: obectron
  thymeleaf.cache: false
  mvc:
    servlet:
      path: /v1/api
  web:
    resources:
      add-mappings: true

server:
  port: 8080
  servlet:
    contextPath: /obectron

# Postgres connection settings
spring.datasource.url: jdbc:postgresql://localhost:5432/obectron
spring.datasource.username: obectron
spring.datasource.password: 7840
spring.datasource.driver-class-name: org.postgresql.Driver

# HikariCP settings
spring.datasource.hikari.minimumIdle: 5
spring.datasource.hikari.maximumPoolSize: 10
spring.datasource.hikari.idleTimeout: 30000
spring.datasource.hikari.maxLifetime: 2000000
spring.datasource.hikari.connectionTimeout: 30000
spring.datasource.hikari.poolName: ObectronHikariPool

# Tomcat settings
spring.datasource.tomcat.maxActive: 15
spring.datasource.tomcat.minIdle: 5

# JPA settings
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL82Dialect
spring.jpa.hibernate.use-new-id-generator-mappings: false
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update

#Logging
logging.level.org.hibernate.SQL: DEBUG
logging.level.com.zaxxer.hikari.HikariConfig: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
